spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: EXE201
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

myapp:
  api-key: 143GuUEp5z3lw3musZsuB97H4qAwEXS9lp62AfK9WcU=

app:
  aws:
    region: ap-southeast-2
    s3:
      bucket: exe201-s3
  jwt:
    secret-base64: ckInpXLuyPjlGUimIoqhIMTyx1ZuCxSQoyIgrEs22dg=

server:
  forward-headers-strategy: native   # Quan trọng: để Spring nhận X-Forwarded-* headers

api-key-webhook-payment: api-key-hello-founderhub-123abc!@@@
