spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: EXE201
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: -1          # không giới hạn
      max-request-size: -1       # không giới hạn

resend:
  api-key: re_ExP57fG1_FJ3MpmjMbRCa5qXhp8te1zp7
  from: "FoundersHub <noreply@foundershub.nducky.id.vn>"

myapp:
  api-key: 143GuUEp5z3lw3musZsuB97H4qAwEXS9lp62AfK9WcU=

app:
  aws:
    region: ap-southeast-2
    s3:
      bucket: exe201-s3
  jwt:
    secret-base64: ckInpXLuyPjlGUimIoqhIMTyx1ZuCxSQoyIgrEs22dg=

server:
  forward-headers-strategy: native   # Quan trọng: để Spring nhận X-Forwarded-* headers
  tomcat:
    max-swallow-size: -1             # không giới hạn swallow size cho file lớn

api-key-webhook-payment: api-key-hello-founderhub-123abc!@@@
