spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: EXE201
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  aws:
    region: ap-southeast-2
    s3:
      bucket: exe201-s3
